server:
  port: 8099
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      default-filters:
      - name: GlobalFilter
      routes:
      - id: service-customer
        uri: http://localhost:9040/
        predicates:
          - Path=/customer/**
        filters:
        - PreFilter
        - PostFilter
  application:
    name: service-apigateway 
          